from data_models import *

# Personal Details:

INVESTMENT_ACCOUNTS = []
CREDIT_CARDS = []
CHECKING_ACCOUNTS = []
SAVING_ACCOUNTS = []
LOANS = []
PAYROLLS = []
TRADITIONAL_IRAS = []
ROTH_IRAS = []
RETIREMENT_401KS = []
ROTH_401KS = []
HSA_ACCOUNTS = []
OTHER_ACCOUNTS = []

# Dictionaries for faster access
INVESTMENT_ACCOUNTS_DICT = {}
CREDIT_CARDS_DICT = {}
CHECKING_ACCOUNTS_DICT = {}
SAVING_ACCOUNTS_DICT = {}
LOANS_DICT = {}
PAYROLLS_DICT = {}
TRADITIONAL_IRAS_DICT = {}
ROTH_IRAS_DICT = {}
RETIREMENT_401KS_DICT = {}
ROTH_401KS_DICT = {}
HSA_ACCOUNTS_DICT = {}
OTHER_ACCOUNTS_DICT = {}
